name: albatrak
description: Let us handle keeping track of your rounds, handicap, rangefinding, club selection and more while you enjoy yourself on your favorite golf course.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amazon_cognito_identity_dart: ^0.0.22
  http: ^0.12.0+2
  provider: ^2.0.1+1
  dio: ^2.1.6
  built_value: ^6.6.0
  get_it: ^1.0.3+1
  fluro: ^1.4.0
  sqflite: ^1.1.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.6.0
  build_runner: ^1.5.0


flutter:
  uses-material-design: true